//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayanFinal.BayanData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BayanTestEntities : DbContext
    {
        public BayanTestEntities()
            : base("name=BayanTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetAllAnswers_Result> GetAllAnswers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAnswers_Result>("GetAllAnswers");
        }
    
        public virtual ObjectResult<GetAllQuestions_Result> GetAllQuestions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllQuestions_Result>("GetAllQuestions");
        }
    
        public virtual ObjectResult<GetAnswers_Result> GetAnswers(Nullable<int> questionID)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("QuestionID", questionID) :
                new ObjectParameter("QuestionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAnswers_Result>("GetAnswers", questionIDParameter);
        }
    
        public virtual ObjectResult<UserLogin_Result> UserLogin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLogin_Result>("UserLogin", userNameParameter, passwordParameter);
        }
    }
}
